### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kanchi12P** [praveenscience/Internship-LMS-FrontEnd#42] opened 2021-03-09 15:35 UTC
I can create a poster for the project.

The poster will attract more people towards the project and it's easy to get ideas regarding the project by overlooking it.

(i am GSSoC'21 participant)

kindly assign this issue to me!!

**Comment by praveenscience** [comment] 2021-03-09 16:05
Wow, interesting idea. A poster for which one? Please let me know? 😊

**Comment by kanchi12P** [comment] 2021-03-09 16:59
a poster for this platform(internship onboard platform)to attract new interns

**Comment by praveenscience** [comment] 2021-03-12 16:32
Closing this as a duplicate of #49.

**Closed by praveenscience** 2021-03-12 16:32 UTC
